#Build APK: Generates debug APK
#Purpose: Creates debug APK artifact
#Runs: Pushes to main
name: Build APK

on:
  push:
    branches: [ main ]                #trigger: pushes to main
  workflow_dispatch:                  #manual triggering, DO NOT REMOVE

jobs:
  build:
    runs-on: ubuntu-latest           
    
    steps:
    #get code
    - name: Checkout code
      uses: actions/checkout@v4
      
    #installs java 17 for gradle plugin
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'      #use Eclipse Temurin JDK
        cache: gradle                #cache Gradle dependencies for later faster builds
        
    #make  Gradle wrapper script executable
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    #build debug APK
    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace
      env:
        JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}   #forces Gradle to use Java 17, DO NOT REMOVE
      
    #upload APK
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug              #show names in Actions artifacts
        path: app/build/outputs/apk/debug/app-debug.apk  #path to built APK
        retention-days: 30           #keep for 30 days
